const FETCH_POST = 'FETCH_POST';
const NEW_POST = 'NEW_POST';
const DELETE_POST = 'DELETE_POST';
const ERROR_MESSAGE = 'ERROR_MESSAGE';
const CLEAR_SUGGESTION = 'CLEAR_SUGGESTION';
const SET_METADATA = 'SET_METADATA'

export { FETCH_POST, NEW_POST, ERROR_MESSAGE, DELETE_POST, CLEAR_SUGGESTION, SET_METADATA };